In [41]:
import numpy as np

In [42]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [43]:
A

array([[10,  8,  5],
       [ 7,  6,  5],
       [11, 10,  8]])

In [44]:
B

array([[ 2,  3,  3],
       [ 2, -1,  0],
       [-2,  2, -2]])

In [45]:
# Поэлементное умножение
A*B

array([[ 20,  24,  15],
       [ 14,  -6,   0],
       [-22,  20, -16]])

In [46]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[26 32 20]
 [16 25 11]
 [26 39 17]]


In [47]:
# Матричное умножение
np.dot(A,B)

array([[26, 32, 20],
       [16, 25, 11],
       [26, 39, 17]])

In [48]:
# Матричное умножение
A@B

array([[26, 32, 20],
       [16, 25, 11],
       [26, 39, 17]])

In [49]:
# Порядок умножения AB != BA
B@A

array([[ 74,  64,  49],
       [ 13,  10,   5],
       [-28, -24, -16]])

In [50]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 6  8  7 10  5]
 [ 5  8  6  6 11]
 [ 8  8  6 10 11]]
B:
 [[ 0  2]
 [-1 -2]
 [-2 -1]
 [-2 -1]
 [ 2 -2]]


In [51]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[-32, -31],
       [-10, -40],
       [-18, -38]])

In [52]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

In [ ]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

In [ ]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

In [ ]:
b@A

In [ ]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

In [ ]:
# матрица Грама ортогональной системы векторов
A@A.T

In [ ]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

In [ ]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

In [ ]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)